
AVQDB = {
	["shareStatusWithGuild"] = true,
	["showEnterButtonWhenSolo"] = false,
	["autoTurnInMarks"] = true,
	["readyCheckReport"] = true,
	["showFootnote"] = false,
	["rapidCountdown"] = false,
	["avqMode"] = "AUTO",
	["debugLogging"] = false,
	["dontObscureBFList"] = false,
	["instanceSummaryReport"] = true,
	["bgidAnnounce"] = false,
	["confirmBeforeCommit"] = false,
	["showGuildMemberInstances"] = true,
	["countdown"] = 5,
	["histogram"] = true,
	["sortStatusBarsByAge"] = false,
	["dontResetBFScrollbarWhenSolo"] = true,
	["ignoreAVChat"] = false,
	["debug"] = false,
	["readyCheckTimeout"] = 3,
	["readyLie"] = false,
}
