
DBMPvP_AllSavedVars = {
	["Dewbs-Westfall"] = {
		["PvPGeneral"] = {
			[0] = {
				["TimerRemaining"] = true,
				["TimerFlagCVoice"] = 0,
				["TimerRemainingTColor"] = 0,
				["HideBossEmoteFrame"] = false,
				["AutoSpirit"] = false,
				["TimerFlagTColor"] = 0,
				["TimerCap"] = true,
				["Timer46392nextTColor"] = 0,
				["TimerFlag"] = true,
				["TimerWinTColor"] = 0,
				["TimerCapCVoice"] = 0,
				["Timer110310cast"] = true,
				["TimerWin"] = true,
				["Enabled"] = true,
				["Timer34709nextCVoice"] = 0,
				["Timer46392nextCVoice"] = 0,
				["TimerWinCVoice"] = 0,
				["TimerRemainingCVoice"] = 0,
				["Timer46392next"] = true,
				["Timer34709nextTColor"] = 0,
				["TimerCapTColor"] = 0,
				["Timer110310castCVoice"] = 0,
				["Timer110310castTColor"] = 0,
				["Timer34709next"] = true,
			},
		},
		["z529"] = {
			[0] = {
				["Enabled"] = true,
			},
		},
		["z489"] = {
			[0] = {
				["Enabled"] = true,
			},
		},
		["z30"] = {
			[0] = {
				["Enabled"] = true,
				["TimerCapCVoice"] = 0,
				["TimerCapTColor"] = 0,
				["AutoTurnIn"] = true,
				["TimerCap"] = true,
			},
		},
	},
	["Ohgnomes-Westfall"] = {
		["z489"] = {
			[0] = {
				["Enabled"] = true,
			},
			[2] = {
				["Enabled"] = true,
			},
		},
		["PvPGeneral"] = {
			[0] = {
				["TimerRemaining"] = true,
				["TimerFlagCVoice"] = 0,
				["TimerRemainingTColor"] = 0,
				["TimerCap"] = true,
				["Timer110310castTColor"] = 0,
				["TimerFlagTColor"] = 0,
				["HideBossEmoteFrame"] = false,
				["Timer46392nextTColor"] = 0,
				["TimerFlag"] = true,
				["TimerWinTColor"] = 0,
				["TimerCapCVoice"] = 0,
				["Timer110310castCVoice"] = 0,
				["TimerWin"] = true,
				["Enabled"] = true,
				["Timer46392nextCVoice"] = 0,
				["Timer34709nextCVoice"] = 0,
				["TimerWinCVoice"] = 0,
				["TimerRemainingCVoice"] = 0,
				["Timer46392next"] = true,
				["Timer34709nextTColor"] = 0,
				["TimerCapTColor"] = 0,
				["Timer110310cast"] = true,
				["AutoSpirit"] = false,
				["Timer34709next"] = true,
			},
			[2] = {
				["TimerRemaining"] = true,
				["TimerFlagCVoice"] = 0,
				["ShowRelativeGameTime"] = true,
				["ShowBasesToWin"] = false,
				["ShowEstimatedPoints"] = true,
				["TimerRemainingTColor"] = 0,
				["TimerCap"] = true,
				["Timer110310castTColor"] = 0,
				["TimerFlagTColor"] = 0,
				["HideBossEmoteFrame"] = false,
				["Timer46392nextTColor"] = 0,
				["Enabled"] = true,
				["TimerWinTColor"] = 0,
				["TimerCapCVoice"] = 0,
				["TimerWinCVoice"] = 0,
				["TimerWin"] = true,
				["Timer46392nextCVoice"] = 0,
				["Timer110310castCVoice"] = 0,
				["Timer34709nextCVoice"] = 0,
				["TimerFlag"] = true,
				["TimerRemainingCVoice"] = 0,
				["Timer46392next"] = true,
				["Timer34709nextTColor"] = 0,
				["TimerCapTColor"] = 0,
				["Timer110310cast"] = true,
				["AutoSpirit"] = false,
				["Timer34709next"] = true,
			},
		},
		["talent2"] = "WARRIOR2",
		["z529"] = {
			[0] = {
				["Enabled"] = true,
			},
			[2] = {
				["Enabled"] = true,
			},
		},
		["z30"] = {
			[0] = {
				["Enabled"] = true,
				["TimerCapCVoice"] = 0,
				["TimerCapTColor"] = 0,
				["AutoTurnIn"] = true,
				["TimerCap"] = true,
			},
			[2] = {
				["Enabled"] = true,
				["AutoTurnIn"] = true,
			},
		},
	},
}
