
NWBdatabase = {
	["profileKeys"] = {
		["Dewbs - Westfall"] = "Default",
		["Dewber - Westfall"] = "Default",
		["Dewb - Westfall"] = "Default",
		["Dewfrost - Pagle"] = "Default",
		["Dewbubble - Westfall"] = "Default",
		["Islandclick - Westfall"] = "Default",
		["Hoard - Westfall"] = "Default",
		["Holydewbs - Westfall"] = "Default",
		["Dewitt - Westfall"] = "Default",
		["Dewshock - Mankrik"] = "Default",
		["Dewbear - Westfall"] = "Default",
		["Ohgnomes - Westfall"] = "Default",
		["Shadewstep - Westfall"] = "Default",
		["Raindew - Westfall"] = "Default",
	},
	["global"] = {
		["Westfall"] = {
			["Horde"] = {
				["flower2"] = 0,
				["rendYell"] = 1597613715,
				["flower6"] = 0,
				["dragon3"] = 0,
				["flower9"] = 0,
				["rendYell2"] = 1597613710,
				["tuber2"] = 0,
				["flower7"] = 0,
				["timerLog"] = {
				},
				["onyYell"] = 1597602713,
				["tuber3"] = 0,
				["tuber5"] = 0,
				["onyTimer"] = 1597602728,
				["zanYell2"] = 0,
				["dragon4"] = 0,
				["flower4"] = 0,
				["rendSource"] = "self",
				["tuber6"] = 0,
				["tuber4"] = 0,
				["onySource"] = "self",
				["rendTimerWho"] = "Borohoro",
				["myChars"] = {
					["Dewb"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Warlock",
						["englishClass"] = "WARLOCK",
						["zanCount"] = 0,
						["level"] = 9,
						["buffs"] = {
						},
						["onyCount"] = 0,
						["race"] = "Undead",
					},
					["Raindew"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Shaman",
						["englishClass"] = "SHAMAN",
						["zanCount"] = 0,
						["buffs"] = {
						},
						["level"] = 1,
						["onyCount"] = 0,
						["race"] = "Orc",
					},
				},
				["tuber1"] = 0,
				["rendTimer"] = 1597613721,
				["dragon1"] = 0,
				["nefTimer"] = 0,
				["onyNpcDied"] = 1597602895,
				["nefYell"] = 0,
				["flower8"] = 0,
				["onyTimerWho"] = "Alteraen",
				["nefNpcDied"] = 0,
				["onyYell2"] = 1597602721,
				["nefYell2"] = 0,
				["layersDisabled"] = {
				},
				["dragon2"] = 0,
				["flower5"] = 0,
				["flower10"] = 0,
				["lastSyncBy"] = "Uddertanker-Westfall",
				["flower1"] = 0,
				["layers"] = {
				},
				["zanYell"] = 0,
				["dmfBuffSettings"] = {
				},
				["flower3"] = 0,
			},
			["Alliance"] = {
				["rendYell"] = 1615336224,
				["flower2"] = 1602204537,
				["Shardchugger-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Iportal-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Vespasianus-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Tosgirlbear-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Magefarquaad-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Avaan-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 1,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Treeowl-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["nefSource"] = "self",
				["tuber4"] = 1601686196,
				["nefTimer"] = 1615823119,
				["tuber2"] = 1602002515,
				["Micklevinge-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Artlock-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Psa-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Yangneetbux-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Forforce-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Kliquer-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Sundere-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["onyYell"] = 1615714016,
				["Ursal-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["onyTimer"] = 1615714031,
				["Mintyshifty-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Dotemup-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["dragon4"] = 1602095367,
				["Dirtnaptyme-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["rendSource"] = "self",
				["Kaby-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Onysummons-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["myChars"] = {
					["Dewbs"] = {
						["rendCount"] = 0,
						["nefCount"] = 32,
						["localizedClass"] = "Mage",
						["onyCount"] = 11,
						["englishClass"] = "MAGE",
						["flaskPowerCount"] = 4,
						["savvyCount"] = 15,
						["songflowerCount"] = 12,
						["race"] = "Gnome",
						["zanCount"] = 59,
						["buffs"] = {
							["Spirit of Zandalar"] = {
								["track"] = false,
								["type"] = "zan",
								["setTime"] = 1611181849,
								["playedCacheSetAt"] = 3446538,
								["timeLeft"] = -62403,
							},
							["Songflower Serenade"] = {
								["track"] = false,
								["type"] = "songflower",
								["setTime"] = 1602003081,
								["playedCacheSetAt"] = 3422125,
								["timeLeft"] = -90416,
							},
							["Slip'kik's Savvy"] = {
								["track"] = false,
								["type"] = "savvy",
								["setTime"] = 1602078332,
								["playedCacheSetAt"] = 3435813,
								["timeLeft"] = -73128,
							},
							["Mol'dar's Moxie"] = {
								["track"] = false,
								["type"] = "moxie",
								["setTime"] = 1602078431,
								["playedCacheSetAt"] = 3435912,
								["timeLeft"] = -73029,
							},
							["Supreme Power"] = {
								["track"] = false,
								["type"] = "flaskPower",
								["setTime"] = 1598401895,
								["playedCacheSetAt"] = 3163007,
								["timeLeft"] = -345934,
							},
							["Fengus' Ferocity"] = {
								["track"] = false,
								["type"] = "ferocity",
								["setTime"] = 1598314900,
								["playedCacheSetAt"] = 3159523,
								["timeLeft"] = -349418,
							},
							["Rallying Cry of the Dragonslayer"] = {
								["track"] = false,
								["type"] = "nef",
								["setTime"] = 1615565798,
								["playedCacheSetAt"] = 3499826,
								["timeLeft"] = -9115,
							},
						},
						["moxieCount"] = 14,
						["level"] = 60,
						["dmfCount"] = 7,
						["ferocityCount"] = 1,
					},
					["Raindew"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Warrior",
						["englishClass"] = "WARRIOR",
						["zanCount"] = 0,
						["race"] = "Night Elf",
						["buffs"] = {
						},
						["onyCount"] = 0,
						["level"] = 1,
					},
					["Dewitt"] = {
						["rendCount"] = 0,
						["nefCount"] = 4,
						["localizedClass"] = "Priest",
						["englishClass"] = "PRIEST",
						["resistFireCount"] = 3,
						["zanCount"] = 1,
						["level"] = 60,
						["buffs"] = {
							["Spirit of Zandalar"] = {
								["track"] = false,
								["type"] = "zan",
								["setTime"] = 1601678965,
								["playedCacheSetAt"] = 1517948,
								["timeLeft"] = -28342,
							},
							["Resist Fire"] = {
								["track"] = false,
								["type"] = "resistFire",
								["setTime"] = 1601683204,
								["playedCacheSetAt"] = 1519607,
								["timeLeft"] = -30283,
							},
							["Rallying Cry of the Dragonslayer"] = {
								["track"] = true,
								["type"] = "ony",
								["setTime"] = 1615609539,
								["playedCacheSetAt"] = 1549331,
								["timeLeft"] = 3041,
							},
						},
						["onyCount"] = 5,
						["race"] = "Human",
					},
					["Shadewstep"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Rogue",
						["englishClass"] = "ROGUE",
						["zanCount"] = 0,
						["onyCount"] = 1,
						["buffs"] = {
							["Rallying Cry of the Dragonslayer"] = {
								["track"] = false,
								["type"] = "ony",
								["setTime"] = 1599173314,
								["playedCacheSetAt"] = 200549,
								["timeLeft"] = -141990,
							},
						},
						["level"] = 43,
						["dmfCount"] = 1,
						["race"] = "Human",
					},
					["Holydewbs"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Paladin",
						["englishClass"] = "PALADIN",
						["zanCount"] = 0,
						["level"] = 1,
						["buffs"] = {
						},
						["onyCount"] = 0,
						["race"] = "Human",
					},
					["Dewbubble"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Paladin",
						["englishClass"] = "PALADIN",
						["zanCount"] = 0,
						["buffs"] = {
						},
						["level"] = 1,
						["onyCount"] = 0,
						["race"] = "Human",
					},
					["Dewber"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Warlock",
						["englishClass"] = "WARLOCK",
						["zanCount"] = 2,
						["level"] = 50,
						["buffs"] = {
							["Spirit of Zandalar"] = {
								["track"] = false,
								["type"] = "zan",
								["setTime"] = 1614638200,
								["playedCacheSetAt"] = 618404,
								["timeLeft"] = -91879,
							},
							["Rallying Cry of the Dragonslayer"] = {
								["track"] = false,
								["type"] = "ony",
								["setTime"] = 1615471646,
								["playedCacheSetAt"] = 668541,
								["timeLeft"] = -41742,
							},
						},
						["onyCount"] = 2,
						["race"] = "Gnome",
					},
					["Islandclick"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Druid",
						["englishClass"] = "DRUID",
						["zanCount"] = 3,
						["level"] = 1,
						["buffs"] = {
							["Spirit of Zandalar"] = {
								["track"] = true,
								["type"] = "zan",
								["setTime"] = 1598398245,
								["playedCacheSetAt"] = 5501,
								["timeLeft"] = 12597,
							},
						},
						["onyCount"] = 0,
						["race"] = "Night Elf",
					},
					["Dewbear"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Druid",
						["englishClass"] = "DRUID",
						["zanCount"] = 0,
						["race"] = "Night Elf",
						["level"] = 1,
						["onyCount"] = 0,
						["buffs"] = {
						},
					},
					["Ohgnomes"] = {
						["rendCount"] = 0,
						["nefCount"] = 2,
						["localizedClass"] = "Warrior",
						["englishClass"] = "WARRIOR",
						["zanCount"] = 9,
						["race"] = "Gnome",
						["buffs"] = {
							["Spirit of Zandalar"] = {
								["track"] = false,
								["type"] = "zan",
								["setTime"] = 1590017008,
								["playedCacheSetAt"] = 1630712,
								["timeLeft"] = -218328,
							},
							["Songflower Serenade"] = {
								["track"] = false,
								["type"] = "songflower",
								["setTime"] = 1598111996,
								["playedCacheSetAt"] = 1805885,
								["timeLeft"] = -46755,
							},
							["Mol'dar's Moxie"] = {
								["track"] = false,
								["type"] = "moxie",
								["setTime"] = 1589243343,
								["playedCacheSetAt"] = 1615756,
								["timeLeft"] = -233284,
							},
							["Fengus' Ferocity"] = {
								["track"] = false,
								["type"] = "ferocity",
								["setTime"] = 1589243300,
								["playedCacheSetAt"] = 1615713,
								["timeLeft"] = -233327,
							},
							["Rallying Cry of the Dragonslayer"] = {
								["track"] = true,
								["type"] = "ony",
								["setTime"] = 1590277640,
								["playedCacheSetAt"] = 1638811,
								["timeLeft"] = -210229,
							},
						},
						["songflowerCount"] = 1,
						["level"] = 60,
						["dmfCount"] = 1,
						["onyCount"] = 4,
					},
					["Hoard"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Mage",
						["englishClass"] = "MAGE",
						["zanCount"] = 0,
						["race"] = "Human",
						["buffs"] = {
						},
						["onyCount"] = 0,
						["level"] = 5,
					},
				},
				["Summonemup-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Dergburger-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Beardrage-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Urnanscrits-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Mysticsadge-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["onySource"] = "self",
				["onyTimerWho"] = "Bambang",
				["Gnarr-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["nefNpcDied"] = 0,
				["tuber5"] = 1601606725,
				["nefYell2"] = 1615643160,
				["nefTimerWho"] = "Qiiuqiiu",
				["Ironbellow-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Takasugi-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Tremblade-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Hotemup-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["faction"] = "Alliance",
				["Forcesac-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Whotfcares-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["dmfBuffSettings"] = {
				},
				["zanYell2"] = 1614638196,
				["timerLog"] = {
				},
				["Clikker-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["flower10"] = 1602200726,
				["flower4"] = 1612310919,
				["Johandarc-Westfall"] = {
					["guildCommand"] = true,
					["disableAllGuildMsgs"] = false,
					["guild15"] = false,
					["guild10"] = true,
					["guild5"] = false,
					["guild0"] = false,
					["guildNpcKilled"] = true,
					["guildBuffDropped"] = true,
					["guild30"] = false,
					["guildSongflower"] = true,
					["guildZanDialogue"] = true,
					["guildNpcDialogue"] = true,
					["guild1"] = true,
				},
				["Arthew-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Summonsquad-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Nyxxie-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Forcelock-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Deadlyfarts-Westfall"] = {
					["guildCommand"] = true,
					["disableAllGuildMsgs"] = false,
					["guild15"] = false,
					["guild10"] = false,
					["guild5"] = false,
					["guild0"] = false,
					["guildNpcKilled"] = true,
					["guildBuffDropped"] = true,
					["guild30"] = false,
					["guildSongflower"] = true,
					["guildZanDialogue"] = false,
					["guildNpcDialogue"] = false,
					["guild1"] = false,
				},
				["Hemet-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Docmcstrange-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["dragon3"] = 1602026942,
				["tuber1"] = 1602022158,
				["rendYell2"] = 1600808422,
				["Mintyclicky-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Naxxprep-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Fyremoon-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Imighttank-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["rendTimerWho"] = "Antho",
				["Eobard-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Mintboy-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["flower7"] = 1602026866,
				["layers"] = {
				},
				["layersDisabled"] = {
				},
				["tuber3"] = 1602200927,
				["Vigne-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["dragon2"] = 1601425645,
				["Haymarn-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Holydew-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Tapris-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Lorkan-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Dewstracting-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Forcebank-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Buckybarnes-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Dewclaws-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["tuber6"] = 1602024918,
				["Stheno-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["nefYell"] = 1615823108,
				["flower1"] = 1602030000,
				["Flustered-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["flower3"] = 1602203079,
				["dragon1"] = 1602032810,
				["Forceshard-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["onyNpcDied"] = 0,
				["Teddyursa-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 1,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["flower8"] = 1602201698,
				["onyYell2"] = 1615714024,
				["rendTimer"] = 1615336229,
				["flower9"] = 1602203039,
				["Bankquaadone-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["Trigist-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["flower5"] = 1602039488,
				["Freezeemup-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 1,
					["guild10"] = 1,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 1,
					["guildNpcKilled"] = 1,
					["guildZanDialogue"] = 1,
					["guildNpcDialogue"] = 1,
					["guild1"] = 1,
				},
				["lastSyncBy"] = "Xristeen-Westfall",
				["Justaway-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["flower6"] = 0,
				["zanYell"] = 1614643226,
				["Midóri-Westfall"] = {
					["guildCommand"] = 1,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = false,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
				["Shortcircuit-Westfall"] = {
					["guildCommand"] = 0,
					["guildBuffDropped"] = 0,
					["guild10"] = 0,
					["guildSongflower"] = 0,
					["disableAllGuildMsgs"] = 0,
					["guildNpcKilled"] = 0,
					["guildZanDialogue"] = 0,
					["guildNpcDialogue"] = 0,
					["guild1"] = 0,
				},
			},
		},
		["autoDmfBuff"] = true,
		["convertSettings"] = false,
		["minimapIcon"] = {
			["minimapPos"] = 166.489231318223,
			["hide"] = true,
		},
		["resetLayers3"] = false,
		["resetSongflowers"] = false,
		["Pagle"] = {
			["Horde"] = {
				["flower2"] = 0,
				["rendYell"] = 0,
				["flower6"] = 0,
				["tuber4"] = 0,
				["flower3"] = 0,
				["rendYell2"] = 0,
				["tuber2"] = 0,
				["flower7"] = 0,
				["layers"] = {
				},
				["layersDisabled"] = {
				},
				["tuber3"] = 0,
				["tuber5"] = 0,
				["onyTimer"] = 0,
				["zanYell2"] = 0,
				["dragon4"] = 0,
				["tuber6"] = 0,
				["nefYell"] = 0,
				["flower1"] = 0,
				["rendTimer"] = 0,
				["dragon1"] = 0,
				["onyYell"] = 0,
				["onyNpcDied"] = 0,
				["myChars"] = {
					["Dewfrost"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Shaman",
						["englishClass"] = "SHAMAN",
						["zanCount"] = 0,
						["race"] = "Troll",
						["buffs"] = {
						},
						["onyCount"] = 0,
						["level"] = 1,
					},
				},
				["flower8"] = 0,
				["timerLog"] = {
				},
				["nefNpcDied"] = 0,
				["flower4"] = 0,
				["nefYell2"] = 0,
				["onyYell2"] = 0,
				["flower9"] = 0,
				["flower5"] = 0,
				["flower10"] = 0,
				["tuber1"] = 0,
				["dragon2"] = 0,
				["dragon3"] = 0,
				["zanYell"] = 0,
				["dmfBuffSettings"] = {
				},
				["nefTimer"] = 0,
			},
		},
		["Mankrik"] = {
			["Alliance"] = {
				["flower2"] = 0,
				["rendYell"] = 0,
				["flower6"] = 0,
				["tuber4"] = 0,
				["flower3"] = 0,
				["rendYell2"] = 0,
				["tuber2"] = 0,
				["flower7"] = 0,
				["layers"] = {
				},
				["onyYell"] = 0,
				["tuber3"] = 0,
				["tuber5"] = 0,
				["onyTimer"] = 0,
				["zanYell2"] = 0,
				["dragon4"] = 0,
				["tuber6"] = 0,
				["nefYell"] = 0,
				["myChars"] = {
					["Dewshock"] = {
						["rendCount"] = 0,
						["nefCount"] = 0,
						["localizedClass"] = "Warrior",
						["englishClass"] = "WARRIOR",
						["zanCount"] = 0,
						["race"] = "Dwarf",
						["level"] = 1,
						["onyCount"] = 0,
						["buffs"] = {
						},
					},
				},
				["rendTimer"] = 0,
				["dragon1"] = 0,
				["timerLog"] = {
				},
				["onyNpcDied"] = 0,
				["dragon3"] = 0,
				["flower8"] = 0,
				["nefTimer"] = 0,
				["nefNpcDied"] = 0,
				["onyYell2"] = 0,
				["nefYell2"] = 0,
				["flower4"] = 0,
				["flower9"] = 0,
				["flower5"] = 0,
				["flower10"] = 0,
				["tuber1"] = 0,
				["dragon2"] = 0,
				["flower1"] = 0,
				["zanYell"] = 0,
				["dmfBuffSettings"] = {
				},
				["layersDisabled"] = {
				},
			},
		},
		["minimapButton"] = false,
		["resetLayerMaps"] = false,
		["lastVersionMsg"] = 1615987244,
		["resetLayers4"] = false,
		["disableAllGuildMsgs"] = 1,
	},
}
