
PawnCommon = {
	["ShowUpgradesOnTooltips"] = true,
	["AlignNumbersRight"] = false,
	["ShowBagUpgradeAdvisor"] = false,
	["ShowItemID"] = false,
	["ShowRelicUpgrades"] = false,
	["ShowValuesForUpgradesOnly"] = true,
	["ShowItemLevelUpgrades"] = false,
	["Digits"] = 1,
	["Debug"] = false,
	["ColorTooltipBorder"] = true,
	["ShowTooltipIcons"] = true,
	["LastVersion"] = 2.0417,
	["ShowSocketingAdvisor"] = true,
	["Scales"] = {
		["\"Classic\":WARRIOR2"] = {
			["PerCharacterOptions"] = {
				["Ohgnomes-Westfall"] = {
					["Visible"] = true,
				},
				["Raindew-Westfall"] = {
					["Visible"] = true,
				},
				["Dewshock-Mankrik"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c69b6d",
			["LocalizedName"] = "Warrior: Fury",
			["ClassID"] = 1,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "947451",
			["SpecID"] = 2,
		},
		["\"Classic\":MAGE3"] = {
			["PerCharacterOptions"] = {
				["Dewbs-Westfall"] = {
					["Visible"] = true,
				},
				["Hoard-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3fc6ea",
			["LocalizedName"] = "Mage: Frost",
			["ClassID"] = 8,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "2f94af",
			["SpecID"] = 3,
		},
		["\"Classic\":WARLOCK2"] = {
			["PerCharacterOptions"] = {
				["Dewb-Westfall"] = {
					["Visible"] = true,
				},
				["Dewber-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8787ed",
			["LocalizedName"] = "Warlock: Demonology",
			["ClassID"] = 9,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "6565b1",
			["SpecID"] = 2,
		},
		["\"Classic\":MAGE1"] = {
			["PerCharacterOptions"] = {
				["Dewbs-Westfall"] = {
					["Visible"] = true,
				},
				["Hoard-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3fc6ea",
			["LocalizedName"] = "Mage: Arcane",
			["ClassID"] = 8,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "2f94af",
			["SpecID"] = 1,
		},
		["\"Classic\":MAGE2"] = {
			["PerCharacterOptions"] = {
				["Dewbs-Westfall"] = {
					["Visible"] = true,
				},
				["Hoard-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3fc6ea",
			["LocalizedName"] = "Mage: Fire",
			["ClassID"] = 8,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "2f94af",
			["SpecID"] = 2,
		},
		["\"Classic\":PALADIN2"] = {
			["PerCharacterOptions"] = {
				["Dewbubble-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f48cba",
			["LocalizedName"] = "Paladin: Protection",
			["ClassID"] = 2,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "b7698b",
			["SpecID"] = 2,
		},
		["\"Classic\":HUNTER2"] = {
			["PerCharacterOptions"] = {
			},
			["Color"] = "aad372",
			["LocalizedName"] = "Hunter: Marksmanship",
			["ClassID"] = 3,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "7f9e55",
			["SpecID"] = 2,
		},
		["\"Classic\":PRIEST1"] = {
			["PerCharacterOptions"] = {
				["Dewitt-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ffffff",
			["LocalizedName"] = "Priest: Discipline",
			["ClassID"] = 5,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfbfbf",
			["SpecID"] = 1,
		},
		["\"Classic\":WARRIOR3"] = {
			["PerCharacterOptions"] = {
				["Ohgnomes-Westfall"] = {
					["Visible"] = true,
				},
				["Raindew-Westfall"] = {
					["Visible"] = true,
				},
				["Dewshock-Mankrik"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c69b6d",
			["LocalizedName"] = "Warrior: Protection",
			["ClassID"] = 1,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "947451",
			["SpecID"] = 3,
		},
		["\"Classic\":WARLOCK3"] = {
			["PerCharacterOptions"] = {
				["Dewb-Westfall"] = {
					["Visible"] = true,
				},
				["Dewber-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8787ed",
			["LocalizedName"] = "Warlock: Destruction",
			["ClassID"] = 9,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "6565b1",
			["SpecID"] = 3,
		},
		["\"Classic\":PRIEST3"] = {
			["PerCharacterOptions"] = {
				["Dewitt-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ffffff",
			["LocalizedName"] = "Priest: Shadow",
			["ClassID"] = 5,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfbfbf",
			["SpecID"] = 3,
		},
		["\"Classic\":SHAMAN2"] = {
			["PerCharacterOptions"] = {
				["Dewfrost-Pagle"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "0270dd",
			["LocalizedName"] = "Shaman: Enhancement",
			["ClassID"] = 7,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "0154a5",
			["SpecID"] = 2,
		},
		["\"Classic\":HUNTER3"] = {
			["PerCharacterOptions"] = {
			},
			["Color"] = "aad372",
			["LocalizedName"] = "Hunter: Survival",
			["ClassID"] = 3,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "7f9e55",
			["SpecID"] = 3,
		},
		["\"Classic\":HUNTER1"] = {
			["PerCharacterOptions"] = {
			},
			["Color"] = "aad372",
			["LocalizedName"] = "Hunter: Beast Mastery",
			["ClassID"] = 3,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "7f9e55",
			["SpecID"] = 1,
		},
		["\"Classic\":WARRIOR1"] = {
			["PerCharacterOptions"] = {
				["Ohgnomes-Westfall"] = {
					["Visible"] = true,
				},
				["Raindew-Westfall"] = {
					["Visible"] = true,
				},
				["Dewshock-Mankrik"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c69b6d",
			["LocalizedName"] = "Warrior: Arms",
			["ClassID"] = 1,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "947451",
			["SpecID"] = 1,
		},
		["\"Classic\":SHAMAN1"] = {
			["PerCharacterOptions"] = {
				["Dewfrost-Pagle"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "0270dd",
			["LocalizedName"] = "Shaman: Elemental",
			["ClassID"] = 7,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "0154a5",
			["SpecID"] = 1,
		},
		["\"Classic\":SHAMAN3"] = {
			["PerCharacterOptions"] = {
				["Dewfrost-Pagle"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "0270dd",
			["LocalizedName"] = "Shaman: Restoration",
			["ClassID"] = 7,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "0154a5",
			["SpecID"] = 3,
		},
		["\"Classic\":PALADIN3"] = {
			["PerCharacterOptions"] = {
				["Dewbubble-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f48cba",
			["LocalizedName"] = "Paladin: Retribution",
			["ClassID"] = 2,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "b7698b",
			["SpecID"] = 3,
		},
		["\"Classic\":ROGUE"] = {
			["Color"] = "fff468",
			["LocalizedName"] = "Rogue: Off Hand",
			["PerCharacterOptions"] = {
				["Shadewstep-Westfall"] = {
					["Visible"] = true,
				},
			},
			["DoNotShow1HUpgrades"] = false,
			["ClassID"] = 4,
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfb74e",
		},
		["\"Classic\":DRUID3"] = {
			["PerCharacterOptions"] = {
				["Dewbear-Westfall"] = {
					["Visible"] = true,
				},
				["Islandclick-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff7c0a",
			["LocalizedName"] = "Druid: Feral (Tank)",
			["ClassID"] = 11,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bf5d07",
			["SpecID"] = 3,
		},
		["\"Classic\":DRUID2"] = {
			["PerCharacterOptions"] = {
				["Dewbear-Westfall"] = {
					["Visible"] = true,
				},
				["Islandclick-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff7c0a",
			["LocalizedName"] = "Druid: Feral (Damage)",
			["ClassID"] = 11,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bf5d07",
			["SpecID"] = 2,
		},
		["\"Classic\":WARLOCK1"] = {
			["PerCharacterOptions"] = {
				["Dewb-Westfall"] = {
					["Visible"] = true,
				},
				["Dewber-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8787ed",
			["LocalizedName"] = "Warlock: Affliction",
			["ClassID"] = 9,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "6565b1",
			["SpecID"] = 1,
		},
		["\"Classic\":DRUID4"] = {
			["PerCharacterOptions"] = {
				["Dewbear-Westfall"] = {
					["Visible"] = true,
				},
				["Islandclick-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff7c0a",
			["LocalizedName"] = "Druid: Restoration",
			["ClassID"] = 11,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bf5d07",
			["SpecID"] = 4,
		},
		["\"Classic\":ROGUE2"] = {
			["PerCharacterOptions"] = {
				["Shadewstep-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fff468",
			["LocalizedName"] = "Rogue: Combat",
			["ClassID"] = 4,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfb74e",
			["SpecID"] = 2,
		},
		["\"Classic\":ROGUE3"] = {
			["PerCharacterOptions"] = {
				["Shadewstep-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fff468",
			["LocalizedName"] = "Rogue: Subtlety",
			["ClassID"] = 4,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfb74e",
			["SpecID"] = 3,
		},
		["\"Classic\":DRUID1"] = {
			["PerCharacterOptions"] = {
				["Dewbear-Westfall"] = {
					["Visible"] = true,
				},
				["Islandclick-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff7c0a",
			["LocalizedName"] = "Druid: Balance",
			["ClassID"] = 11,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bf5d07",
			["SpecID"] = 1,
		},
		["\"Classic\":PALADIN1"] = {
			["PerCharacterOptions"] = {
				["Dewbubble-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f48cba",
			["LocalizedName"] = "Paladin: Holy",
			["ClassID"] = 2,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "b7698b",
			["SpecID"] = 1,
		},
		["\"Classic\":ROGUE1"] = {
			["PerCharacterOptions"] = {
				["Shadewstep-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fff468",
			["LocalizedName"] = "Rogue: Assassination",
			["ClassID"] = 4,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfb74e",
			["SpecID"] = 1,
		},
		["\"Classic\":PRIEST2"] = {
			["PerCharacterOptions"] = {
				["Dewitt-Westfall"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ffffff",
			["LocalizedName"] = "Priest: Holy",
			["ClassID"] = 5,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = false,
			["Provider"] = "Classic",
			["UnenchantedColor"] = "bfbfbf",
			["SpecID"] = 2,
		},
	},
	["IgnoreGemsWhileLeveling"] = true,
	["ButtonPosition"] = 2,
	["ShowLootUpgradeAdvisor"] = true,
	["ShowQuestUpgradeAdvisor"] = true,
	["ShowSpecIcons"] = true,
	["ShownGettingStarted"] = true,
}
